//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingToolBox {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class BillingToolBoxSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static BillingToolBoxSettings defaultInstance = ((BillingToolBoxSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BillingToolBoxSettings())));
        
        public static BillingToolBoxSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Billing WindowsServiceConsole</string>
  <string>Billing WindowsServiceCorrespondence</string>
  <string>Billing WindowsServiceInterface</string>
  <string>Billing WindowsServicePolicyTransactionPublisher</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Services {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Services"]));
            }
            set {
                this["Services"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Work\\DevPathTable\\BillingDecisions_CentralConfig.xml")]
        public string BDCentralConfigLocation {
            get {
                return ((string)(this["BDCentralConfigLocation"]));
            }
            set {
                this["BDCentralConfigLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial " +
            "Catalog=master;Data Source=HFDSREYNOLDSW7D\\SQLSERVER")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>CMD--C:\Work\Products\DailyBuild\Bin\insurity.billing.consoleapplicationinterface.exeARG--,/checkdisbursementexport,/checkdisbursementimport,/checkdisbursementimport /importfilename,/collectionexport,/dailyrun,/dailyrun /invoicedate&lt;DATE&gt;,/donotacceptexport,/eftexport,/eftexport /eftdate=&lt;DATE&gt;,/eftexport /regenerate=&lt;ID&gt;,/generalledgerexport,/lockboximportdirectbill,/lockboximportdirectbill /importfilename,/lockboximportaccountbill,/lockboximportaccountbill /importfilename,/monthlyrundirectbill /accountinggroupcode,/monthlyrunagencybill /accountinggroupcode,/paymentexport,/paymentimportagencybill /importfilepath,/paymentimportdirectbill,/paymentimportpayrolldeduct,/recurringbatch,/recurringsend,/recurringimport</string>
  <string>CMD--C:\QuickLaunch\SprocsAndBats\Merge\mergSqlFilesAutoEDIT.cmd</string>
  <string>CMD--C:\QuickLaunch\SprocsAndBats\Merge\mergerunonEDIT.cmd</string>
  <string>CMD--C:\Work\Products\DailyBuild\BillingLegacy\NetSource\ExternalInterface.Console\obj\Debug\Insurity.BillingDecisions.ExternalInterface.Console.exeARG--COL,PAY,DNA,GL</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CommandTable {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CommandTable"]));
            }
            set {
                this["CommandTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Work\\DevPathTable\\BDServicebusConfig.xml")]
        public string BDServiceBusConfigLocation {
            get {
                return ((string)(this["BDServiceBusConfigLocation"]));
            }
            set {
                this["BDServiceBusConfigLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Work\\Products\\DailyBuild\\Billing\\Database\\BDD")]
        public string BDD_Directory {
            get {
                return ((string)(this["BDD_Directory"]));
            }
            set {
                this["BDD_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>TableScripts</string>
  <string>Functions</string>
  <string>Views</string>
  <string>StoredProcs</string>
  <string>Indexes</string>
  <string>DataScripts</string>
  <string>RunEveryTime</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MergeFolders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MergeFolders"]));
            }
            set {
                this["MergeFolders"] = value;
            }
        }
    }
}
